# Generated by Django 5.1.6 on 2025-05-05 12:45

from django.db import migrations


def fill_nulls(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    Category = apps.get_model('blog', 'Category')
    
    
    # Set default text for null descriptions
    Post.objects.filter(description__isnull=True).update(description="No description provided.")
    

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.RunPython(fill_nulls),
    ]
